import json
from pathlib import Path

from auditor.llm_client import create_client
from auditor.parser import read_terraform_file
from auditor.checkov_parser import parse_checkov_results


def load_prompt() -> str:
    prompt_path = Path(
        "prompts/terraform_security.txt"
    )

    return prompt_path.read_text(
        encoding="utf-8"
    )


def audit_terraform(file_path: str):

    terraform_code = read_terraform_file(
        file_path
    )

    security_prompt = load_prompt()

    checkov_findings = parse_checkov_results(
        "checkov-results.json"
    )

    checkov_context = json.dumps(
        checkov_findings,
        indent=2
    )

    client = create_client()

    response = client.converse(
        modelId="amazon.nova-lite-v1:0",

        messages=[
            {
                "role": "user",

                "content": [
                    {
                        "text": (
                            f"{security_prompt}\n\n"

                            "Review the following "
                            "Terraform code.\n\n"

                            f"```terraform\n"
                            f"{terraform_code}\n"
                            f"```\n\n"

                            "The following security findings "
                            "were generated by Checkov.\n\n"

                            f"```json\n"
                            f"{checkov_context}\n"
                            f"```"
                        )
                    }
                ],
            }
        ],

        inferenceConfig={
            "maxTokens": 2000,
            "temperature": 0,
        },
    )

    result = response[
        "output"
    ][
        "message"
    ][
        "content"
    ][0]["text"]

    # Remove Markdown code fences
    result = result.strip()

    if result.startswith("```json"):
        result = result[
            len("```json"):
        ].strip()

    if result.endswith("```"):
        result = result[:-3].strip()

    try:

        return json.loads(result)

    except json.JSONDecodeError:

        return {
            "status": "ERROR",
            "raw_response": result,
        }


if __name__ == "__main__":

    import sys

    if len(sys.argv) != 2:

        print(
            "Usage: python -m auditor.auditor "
            "<terraform-file>"
        )

        sys.exit(1)

    terraform_file = sys.argv[1]

    result = audit_terraform(
        terraform_file
    )

    print(
        json.dumps(
            result,
            indent=2
        )
    )