name: AI Terraform Security Review

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:

  terraform-security:

    name: Terraform Security Review

    runs-on: ubuntu-latest
    environment: DEV

    steps:

      # --------------------------------------------------
      # 1. Checkout repository
      # --------------------------------------------------

      - name: Checkout
        uses: actions/checkout@v7


      # --------------------------------------------------
      # 2. Setup Python
      # --------------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"


      # --------------------------------------------------
      # 3. Upgrade pip
      # --------------------------------------------------

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip


      # --------------------------------------------------
      # 4. Install project dependencies
      # --------------------------------------------------

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # --------------------------------------------------
      # 5. Configure AWS credentials using GitHub OIDC
      # --------------------------------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}


      # --------------------------------------------------
      # 6. Verify AWS identity
      # --------------------------------------------------

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity


      # --------------------------------------------------
      # 7. Run AI Terraform Security Reviewer
      #
      # auditor.auditor performs:
      #
      # Terraform
      #     ↓
      # Checkov
      #     ↓
      # Checkov Parser
      #     ↓
      # Security Gate
      #     ↓
      # Amazon Bedrock Nova
      #     ↓
      # Security Report
      #
      # --------------------------------------------------

      - name: AI Terraform Security Review
        env:
          AWS_REGION: ap-south-1
        run: |
          python -m auditor.auditor examples/vulnerable.tf